name: chat_view
description: Chat View feature
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  domain:
    path: ../../domain
  core_ui:
    path: ../../core_ui
  navigation:
    path: ../../navigation

  easy_localization: ^3.0.2
  file_picker: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
